import type { Metadata } from "next";
import "./globals.css";
import Navbar from "@/components/Navbar";




export const metadata: Metadata = {
  title: "Call Audio App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body>
        <div className="container mx-auto">
          <Navbar />
          {children}
        </div>
      </body>
    </html>
  );
}
